### ISSUE TITLE
add sending, receiving and printing to stdout for FDMI records using hardcoded filter and hardcoded endpoints

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#889]
- The purpose of the task is to make FDMI-based DIX path work
  - The task

    - work continues in ``fdmi-plugin-multisite`` branch in Motr repo
    - single node setup with Motr/Hare is being used
    - make an FDMI filter that matches everything it receives
    - attach the filter on FDMI source side
    - make a new FDMI plugin that prints to stdout FDMI records received in hex
    - initialise and start the plugin in ``m0sched`` application
    - hardcode endpoints for FDMI everywhere, don't use configuration
    - run ``m0crate`` workload for DIX workload and ensure that FDMI records
      for this workload are printed to stdout
    - extend ``doc/m0sched.rst`` document information on how to see FDMI
      records printed
    - post ``m0crate`` configuration and ``m0sched`` output to this issue

  - Definition of done

    - ``doc/m0sched.rst`` in ``fdmi-plugin-multisite`` repo describes how to
      run ``m0crate`` with DIX workload and ``m0sched`` together
    - steps from the document are reproducible
    - ``m0sched`` prints every received FDMI record in hex to stdout if it's
      executed as described in ``doc/m0sched.rst``
    - this issue has ``m0crate`` yaml configuration file and ``m0sched`` output
  
  - Notes

    - deduplication is not a part of this task
    - record persistence or failure handling on source or target side are not a
      part of this task

  - References

    - https://github.com/Seagate/cortx-motr/blob/main/fdmi/fdmi.c#L24

**Comment by somnathbghule** [comment]
Please find task completion details:

1. created hardcoded filter with hardcoded endpoint at FDMI source side.
2.  initialized and started the plugin in m0sched application.
3. run m0crate workload 

On each fol record receive at plugin application side(m0sched), m0sched will create a filename with fol_rec_m0sched_* in /tmp directory.
```
[root@devvm temp]# ls /tmp/fol_rec*
/tmp/fol_rec_BE_0x7fd8a3ffe880_13  /tmp/fol_rec_BE_0x7fd922ff4880_14      /tmp/fol_rec_m0sched_0x7fd4127f3b70_4
/tmp/fol_rec_BE_0x7fd8c37fd880_12  /tmp/fol_rec_m0sched_0x7fd4127f3b70_2  /tmp/fol_rec_m0sched_0x7fd4127f3b70_5
/tmp/fol_rec_BE_0x7fd8e1ffa880_11  /tmp/fol_rec_m0sched_0x7fd4127f3b70_3
[root@devvm temp]# ls /tmp/fol_rec_BE*
/tmp/fol_rec_BE_0x7fd8a3ffe880_13  /tmp/fol_rec_BE_0x7fd8e1ffa880_11
/tmp/fol_rec_BE_0x7fd8c37fd880_12  /tmp/fol_rec_BE_0x7fd922ff4880_14
[root@devvm temp]# ls /tmp/fol_rec_m0sched*
/tmp/fol_rec_m0sched_0x7fd4127f3b70_2  /tmp/fol_rec_m0sched_0x7fd4127f3b70_4
/tmp/fol_rec_m0sched_0x7fd4127f3b70_3  /tmp/fol_rec_m0sched_0x7fd4127f3b70_5
[root@devvm temp]#

[root@devvm temp]# strings /tmp/fol_rec_m0sched* | grep 'fid\|cr_nr\|cr_key\|cr_val'
		fid:<5400000200000000:2>
		cr_nr: 1
		cr_key: 16 bytes
		cr_val: 80 bytes
		fid:<5400000200000001:a>
		cr_nr: 3
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes cVKRQ19xh9O7MHj4Dudf0o0tWenuHZU
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes SSCHJEQgVX22KKjOlN1ANnBeiNCMuzE
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes ksh19TRnOPpPz76lsSl1DGCSWpuGR1l
		fid:<5400000200000001:a>
		cr_nr: 3
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes ctAdAr3XfQl2nq7GRZ1SCGuuCRWjGYC
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes Spa4YB5VOVePiFWYuVYmvCO0eFUvjS5
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes agfceOh7DckssZmorhkNMWBK9eFEvvI
		fid:<5400000200000001:a>
		cr_nr: 3
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes FJVRVK83linLIk77Lmrw8m7Rvju7OXP
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes uHLjCvqDOIYzpiGu12Tx8fCZKTrQIpF
		cr_key: 20 bytes AAAA
		cr_val: 32 bytes a4qrETRiHyegXvUrwWk23AE2iws8cRM
```
**m0sched output**		
```
[root@devvm temp]# m0sched -l 192.168.52.53@tcp:12345:4:1 -h 192.168.52.53@tcp:12345:1:1 -p 0x7000000000000001:0x37 -f 0x7200000000000001:0x19
Plugin registration rc: 0
m0sched waiting for signal...
============plugin called====================
============plugin called====================
============plugin called====================
============plugin called====================
```		
**m0crate yaml configuration file**
```
# m0crate index .yaml
# Number of clients and server nodes - TBD. Layout with replication factor 1.
# Keys order: ordered.

CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: 192.168.52.53@tcp:12345:4:2
   MOTR_HA_ADDR:    192.168.52.53@tcp:12345:1:1
   PROF: <0x7000000000000001:0x37>      # Profile fid
   LAYOUT_ID: 1                         # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                        # Is oostore-mode?
   IS_READ_VERIFY: 0                    # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16                    # Minimum length of the receive queue
   M0_MAX_RPC_MSG_SIZE: 262144                  # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x19>
   IDX_SERVICE_ID: 1

WORKLOAD_SPEC:                                  # Workload specification section
   WORKLOAD:                                    # First Workload
        WORKLOAD_TYPE: 0                        # Index(0), IO(1)
        WORKLOAD_SEED: tstamp                   # SEED to the random number generator
        NUM_KVP: 3                                      # int
        NXRECORDS: default                                      # int or default
        OP_COUNT: 3                                     # int [units] or unlimited, total operations count.
        EXEC_TIME: unlimited                    # int (seconds) or unlimited
        WARMUP_PUT_CNT: 0                               # int (ops) or all
        WARMUP_DEL_RATIO: 0                     # int (ops / ratio)
        KEY_PREFIX: 1                                   # int or random
        KEY_ORDER:  ordered                     # ordered or random
        KEY_SIZE: 20                                    # int or random
        VALUE_SIZE: 32                          # int or random
        MAX_KEY_SIZE: 16384                                     # int
        MAX_VALUE_SIZE: 32768                           # int
        INDEX_FID: <7800000000000001:a> # fid
        PUT:  100                                                       # int (in percentage)
        DEL:  00                                                        # int (in percentage)
        GET:  00                                                        # int (in percentage)
        NEXT: 00                                                        # int (in percentage)
        LOG_LEVEL: 4                                            # err(0), warn(1), info(2), trace(3), debug(4)

```
**Note:** 
cas recs AT buffer finalization has been shifted to cas_fin(), because early AT buffer finalization (at FOL_RECORD_ADD PHASE) gives zeroed keys and values at plugin side (m0sched).
