### ISSUE TITLE
send all KVS put records over FDMI and decode them at plugin side

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#890]

**Comment by somnathbghule** [comment]
Please find latest update on this,

- I used hardcoded filter at fdmi source side to send fdmi source records to plugin **m0sched** continuously.

-  Extracted index fid and kv pairs from the fol records in **m0sched** and printed in json format as shown below. 

**m0sched output**
```
[root@devvm temp]# m0sched -l 192.168.52.53@tcp:12345:4:1 -h 192.168.52.53@tcp:12345:1:1 -p 0x7000000000000001:0x37 -f 0x7200000000000001:0x19
Plugin registration rc: 0
m0sched waiting for signal...
{ "fid": <5400000200000000:2>, "cr_key": 7800000000000001b, "cr_val":  }
{ "fid": <5400000200000001:b>, "cr_key": AAAAAAAAAAAAAAAA80, "cr_val": kd0miHdmJ4aGc0xywD6cZQrLig1DYPK }
{ "fid": <5400000200000001:b>, "cr_key": AAAAAAAAAAAAAAAA81, "cr_val": h3KDjpOD6TNM3NhzhUFuRtTAM9zp6p7 }
{ "fid": <5400000200000001:b>, "cr_key": AAAAAAAAAAAAAAAA82, "cr_val": nqPYHeMlkD84HUlebdUD2nxD7EcuIBB }
{ "fid": <5400000200000001:b>, "cr_key": AAAAAAAAAAAAAAAA83, "cr_val": 5Zo1HAM2Sp8W42hjesbPvwm8EZk6HUG }
{ "fid": <5400000200000001:b>, "cr_key": AAAAAAAAAAAAAAAA84, "cr_val": LT4MyFyyxWHu0HJhTcsJHX3Pz27FK1l }
{ "fid": <5400000200000000:2>, "cr_key": 7800000000000001c, "cr_val":  }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA80, "cr_val": yO6g1wJmkOUq22n1UickulA43Prz9UN }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA81, "cr_val": HGRVFnF2GrU4tUpuOHG6b0Fg3uFADxm }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA82, "cr_val": ledgTBTTfkLjOGIguoVBxVgLWIqulWQ }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA83, "cr_val": Ea4T1DMTQ5E9TkP7Pb2oJXCuRkTmFPa }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA84, "cr_val": iZebYPXRD2wMTQA1DJ31sZDXOVOaBDl }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA85, "cr_val": RCx2ylZqY0UJRKhQo0SntPZoDUcOtP7 }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA86, "cr_val": kpEmXXklWifF9YWYkUQHnFEJizV40Ib }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA87, "cr_val": l7OF3LXmHfCknyelS9bzuQce6L7bLQk }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA88, "cr_val": 4V8KWUHjzVTUir6DjdOQIC2WIL3RxRc }
{ "fid": <5400000200000001:c>, "cr_key": AAAAAAAAAAAAAAAA89, "cr_val": zNkhJcX0MSTEaiINBWzqEbsyRczHHpR }
```

**m0crate yaml configuration file**
```
# m0crate index .yaml
# Number of clients and server nodes - TBD. Layout with replication factor 1.
# Keys order: ordered.

CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: 192.168.52.53@tcp:12345:4:2
   MOTR_HA_ADDR:    192.168.52.53@tcp:12345:1:1
   PROF: <0x7000000000000001:0x37>      # Profile fid
   LAYOUT_ID: 1                         # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                        # Is oostore-mode?
   IS_READ_VERIFY: 0                    # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16                    # Minimum length of the receive queue
   M0_MAX_RPC_MSG_SIZE: 262144                  # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x19>
   IDX_SERVICE_ID: 1

WORKLOAD_SPEC:                                  # Workload specification section
   WORKLOAD:                                    # First Workload
        WORKLOAD_TYPE: 0                        # Index(0), IO(1)
        WORKLOAD_SEED: tstamp                   # SEED to the random number generator
        NUM_KVP: 1                                      # int
        NXRECORDS: default                                      # int or default
        OP_COUNT: 10                                    # int [units] or unlimited, total operations count.
        EXEC_TIME: unlimited                    # int (seconds) or unlimited
        WARMUP_PUT_CNT: 0                               # int (ops) or all
        WARMUP_DEL_RATIO: 0                     # int (ops / ratio)
        KEY_PREFIX: 8                                   # int or random
        KEY_ORDER:  ordered                     # ordered or random
        KEY_SIZE: 32                                    # int or random
        VALUE_SIZE: 32                          # int or random
        MAX_KEY_SIZE: 16384                                     # int
        MAX_VALUE_SIZE: 32768                           # int
        INDEX_FID: <7800000000000001:c> # fid
        PUT:  100                                                       # int (in percentage)
        DEL:  00                                                        # int (in percentage)
        GET:  00                                                        # int (in percentage)
        NEXT: 00                                                        # int (in percentage)
        LOG_LEVEL: 4                                            # err(0), warn(1), info(2), trace(3), debug(4)
```
