### ISSUE TITLE
a Python script to run m0sched and to process kv pairs received from Motr over FDMI

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#891]
- The purpose of the task is to make a path from FDMI code in C to scheduler
    code in Python for kv pairs received over FDMI.
  - The task

    - work continues in ``fdmi-plugin-multisite`` branch in Motr repo
    - single node setup with Motr/Hare is being used
    - add a Python 3 script ``m0scheduler`` which:

      - gets ``m0sched`` parameters from Hare
      - runs ``m0sched`` and attaches to it's stdin and stdout
      - gets ``m0sched`` stdout and parses JSONs produced by ``m0sched``
      - caches all kv pairs received from ``m0sched`` in memory and
        deduplicates newly received kv pairs using this cache
      - prints deduplicated kv pairs to stdout
      - on ``SIGINT`` sends ``SIGINT`` to ``m0sched``, then waits for it's
        termination, then exits
      - does similar thing on ``SIGTERM``
      - is added to Motr rpm by default

    - add documentation about how to run the script to ``doc/m0sched.rst``
    - use ``m0crate`` to create DIX PUT and DIX GET load
    - ensure that ``m0scheduler`` prints the right kv pairs
    - add ``m0crate`` code to print kv pairs to stdout to check that
      ``m0scheduler`` prints the right kv pairs
    - add ``m0crate`` configuration file and ``m0scheduler`` output to this
      issue

  - Definition of done

    - ``fdmi-plugin-multisite`` branch in Motr repo contains ``m0scheduler``
    - ``m0scheduler`` is installed by default in Motr rpm
    - ``doc/m0sched.rst`` contains documentation on how to run ``m0scheduler``
      and the steps are reproducible
    - ``m0scheduler`` prints deduplicated kv pairs to stdout
    - ``m0crate`` configuration file and ``m0scheduler`` output are added to
      this issue

  - Notes

    - record persistence or failure handling on source or target side are not a
      part of this task

**Comment by somnathbghule** [comment]
Please find update on task completion:
- m0scheduler python3 script created in fdmi/plugins source dir, will be installed by default in motr rpm.
-  updated doc/m0sched with m0scheduler details.
-  m0scheduler execution prints dedup kv records.

**m0crate config file**
```
# m0crate index .yaml
# Number of clients and server nodes - TBD. Layout with replication factor 1.
# Keys order: ordered.

CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: 192.168.52.53@tcp:12345:4:2
   MOTR_HA_ADDR:    192.168.52.53@tcp:12345:1:1
   PROF: <0x7000000000000001:0x37>      # Profile fid
   LAYOUT_ID: 1                         # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                        # Is oostore-mode?
   IS_READ_VERIFY: 0                    # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16                    # Minimum length of the receive queue
   M0_MAX_RPC_MSG_SIZE: 262144                  # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x19>
   IDX_SERVICE_ID: 1

WORKLOAD_SPEC:                                  # Workload specification section
   WORKLOAD:                                    # First Workload
        WORKLOAD_TYPE: 0                        # Index(0), IO(1)
        WORKLOAD_SEED: tstamp                   # SEED to the random number generator
        NUM_KVP: 2                                      # int
        NXRECORDS: default                                      # int or default
        OP_COUNT: 20                                    # int [units] or unlimited, total operations count.
        EXEC_TIME: unlimited                    # int (seconds) or unlimited
        WARMUP_PUT_CNT: 0                               # int (ops) or all
        WARMUP_DEL_RATIO: 0                     # int (ops / ratio)
        KEY_PREFIX: 5                                   # int or random
        KEY_ORDER:  ordered                     # ordered or random
        KEY_SIZE: 32                                    # int or random
        VALUE_SIZE: 32                          # int or random
        MAX_KEY_SIZE: 16384                                     # int
        MAX_VALUE_SIZE: 32768                           # int
        INDEX_FID: <7800000000000001:b> # fid
        PUT:  50                                                        # int (in percentage)
        DEL:  00                                                        # int (in percentage)
        GET:  50                                                        # int (in percentage)
        NEXT: 00                                                        # int (in percentage)
        LOG_LEVEL: 4                                            # err(0), warn(1), info(2), trace(3), debug(4)
```

**m0scheduler output**
```
dedup data:

[root@devvm temp]# m0scheduler
192.168.52.53@tcp:12345:4:1 192.168.52.53@tcp:12345:1:1 0x7000000000000001:0x37 0x7200000000000001:0x19
dedup:  {'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001000000000000000', 'cr_
val': '39384b61543459525757434939314b67744b4441633139577370444d48565a00'} {'fid': '01000000020000540b00000000000000', 'cr_key': '41414
14141414141414141414141414105000000000000001000000000000000', 'cr_val': '503465306e48553777564e6149727951434a524650477034686a746834777
900'}
dedup:  {'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001100000000000000', 'cr_
val': '51314930554d574b48546d70306c39654f54526e345377306956423544753200'} {'fid': '01000000020000540b00000000000000', 'cr_key': '41414
14141414141414141414141414105000000000000001100000000000000', 'cr_val': '55794b5356734e3257474e346d664363526a3175364954615862426666354
e00'}
dedup:  {'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001200000000000000', 'cr_
val': '72774b716f786b3865627444394d4b6f42456659493673476f6c6672574a7300'} {'fid': '01000000020000540b00000000000000', 'cr_key': '41414
14141414141414141414141414105000000000000001200000000000000', 'cr_val': '374478307a584c7a54706e584c43785872525a5658464e3643594652624c4
300'}
dedup:  {'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001300000000000000', 'cr_val': '6d66634d43483449546762757059664e78523174783754647465735639396e00'} {'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001300000000000000', 'cr_val': '686f6168563530745a70515561717337506a344b654876696b745939444a4d00'}

cache kv records:
^CCTRL + C pressed

[{'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001000000000000000', 'cr_val': '39384b61543459525757434939314b67744b4441633139577370444d48565a00'}, 
{'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001100000000000000', 'cr_val': '51314930554d574b48546d70306c39654f54526e345377306956423544753200'}, 
{'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001200000000000000', 'cr_val': '72774b716f786b3865627444394d4b6f42456659493673476f6c6672574a7300'}, 
{'fid': '01000000020000540a00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000001300000000000000', 'cr_val': '6d66634d43483449546762757059664e78523174783754647465735639396e00'}, 
{'fid': '00000000020000540200000000000000', 'cr_key': '01000000000000780b00000000000000', 'cr_val': '020000000200000001000000000000762a000000000000000100000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000000000000000000', 'cr_val': '32437469527942474433505731546a373043665463696b6c3867415748616a00'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000100000000000000', 'cr_val': '4b4b4e30436c4267594435534558634c584f30525967396a6d70526836314100'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000200000000000000', 'cr_val': '4f4d6e4d6d486f41443146774641476f79756e707342794c595643665a435000'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000300000000000000', 'cr_val': '4d6d627947515567725654587975425632356770765056654e4f50304c704f00'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000400000000000000', 'cr_val': '784c5836704e30466555776171304c6a30507a6e696e697661346b3951485800'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000500000000000000', 'cr_val': '6e7355725046717552695931495a4c305841786c5155426c35474463756b3700'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000600000000000000', 'cr_val': '524b31687a454831765a307646586746554f626443354e5961727a6b56557200'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000700000000000000', 'cr_val': '4b4371316334476479446233683868553133356346625a426a7162456c333500'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000800000000000000', 'cr_val': '3646773550794d31346e6337456a6d7a6b6e4577334e774337554c4c654d4f00'},
 {'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000900000000000000', 'cr_val': '6971696e6652376556767231374b6c47324a6a794b36326b6458365762514c00'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000a00000000000000', 'cr_val': '7467314f755155494d70374c75503662524e736f767971514b6c5545754b6e00'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000b00000000000000', 'cr_val': '5631704b746643625a31684b743650455941346d36424b576c36515a79796c00'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000c00000000000000', 'cr_val': '75784b63305a4f615a4e72486778755474355850397979335243525061706100'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000d00000000000000', 'cr_val': '45585551585245374f7079754734597a7831776c613354645376344844735000'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000e00000000000000', 'cr_val': '697048366b7a4a716c3857504f304d6c794e515257544b394c64637251456700'}, 
{'fid': '01000000020000540b00000000000000', 'cr_key': '4141414141414141414141414141414105000000000000000f00000000000000', 'cr_val': '363159626c76554c51324745504771616362303337524c66425772324c336700'}]
```
