### ISSUE TITLE
FDMI records are filtered on FDMI source side with a simple hardcoded filter

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#893]
- The purpose of the task is to show how filtering on FDMI source side works
  - The task

    - Make the following setup: Motr, Hare, S3server, ``m0scheduler``.
    - Add a simple ``strstr()`` -based hardcoded filter on FDMI source side to
      filter ``save_metadata()`` DIX PUT records and send only them, discarding
      the rest of DIX PUT records
    - Run ``s3bench`` to create S3 workload
    - Ensure that ``m0scheduler`` receives only ``save_metadata()`` kv pairs
    - Add ``s3bench`` invocation command and ``m0scheduler`` output to this
      issue

  - Definition of done

    - Setup details are documented in this issue
    - ``s3bench`` command line and ``m0scheduler`` output for this ``s3bench``
      command are added to this issue
    - It's clearly visible that only ``save_metadata()`` DIX PUT operations
      generated by S3server are printed by ``m0scheduler``

  - Notes

    - record persistence or failure handling on source or target side are not a
      part of this task

**Comment by somnathbghule** [comment]
Please find update on task completion details:

- Added simple filter to filter s3 object (save_metadata) a hardcoded filter on FDMI source side 
- To start with created another simple filter for m0crate  to filter kv records  based on matching key pattern, pasting output for the same,
```
[root@devvm temp]# m0scheduler
192.168.52.53@tcp:12345:4:1 192.168.52.53@tcp:12345:1:1 0x7000000000000001:0x37 0x7200000000000001:0x19
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00', 'cr_val': 'Kql5aM1lT4Ac9X07sUgwQAXIwTcoioY'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00',
 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'cr_val': 'UFquJlBrdH4CbmwtAGCmL8rwNzl9Jha'}
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00
\x00\x00\x00\x00\x00', 'cr_val': '0Ni4X45gV9Q7gL5ndZBHO9EuGxH2N5Y'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00',
 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00', 'cr_val': 'DWz5EUG57n9HwtdY1RAnBHM5umqD3FM'}
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00', 'cr_val': 'Kql5aM1lT4Ac9X07sUgwQAXIwTcoioY'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'cr_val': 'EzlKdfqikMp1gQceR2NcDuZIYj6CmLo'}
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00', 'cr_val': '0Ni4X45gV9Q7gL5ndZBHO9EuGxH2N5Y'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00', 'cr_val': '0kHKwU9OeVcd92poSpb42F3IBmObGxx'}
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'cr_val': 'Kql5aM1lT4Ac9X07sUgwQAXIwTcoioY'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'cr_val': 'HQepm8y8krkxzlVXdk6flLj3kDQwkl3'}
dedup:  {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00', 'cr_val': '0Ni4X45gV9Q7gL5ndZBHO9EuGxH2N5Y'} {'fid': '\x01\x00\x00\x00\x02\x00\x00T\n\x00\x00\x00\x00\x00\x00', 'cr_key': 'AAAAAAAA\x05\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00', 'cr_val': 'ZbiovoVEJkWeTf9OqsUGNDXOYAEuS0x'}
```
- pasting m0scrate workload config file

```
# m0crate index .yaml
# Number of clients and server nodes - TBD. Layout with replication factor 1.
# Keys order: ordered.

CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: 192.168.52.53@tcp:12345:4:2
   MOTR_HA_ADDR:    192.168.52.53@tcp:12345:1:1
   PROF: <0x7000000000000001:0x37>      # Profile fid
   LAYOUT_ID: 1                         # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                        # Is oostore-mode?
   IS_READ_VERIFY: 0                    # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16                    # Minimum length of the receive queue
   M0_MAX_RPC_MSG_SIZE: 262144                  # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x19>
   IDX_SERVICE_ID: 1

WORKLOAD_SPEC:                                  # Workload specification section
   WORKLOAD:                                    # First Workload
        WORKLOAD_TYPE: 0                        # Index(0), IO(1)
        WORKLOAD_SEED: tstamp                   # SEED to the random number generator
        NUM_KVP: 2                                      # int
        NXRECORDS: default                                      # int or default
        OP_COUNT: 40                                    # int [units] or unlimited, total operations count.
        EXEC_TIME: unlimited                    # int (seconds) or unlimited
        WARMUP_PUT_CNT: 0                               # int (ops) or all
        WARMUP_DEL_RATIO: 0                     # int (ops / ratio)
        KEY_PREFIX: 5                                   # int or random
        KEY_ORDER:  ordered                     # ordered or random
        KEY_SIZE: 24                                    # int or random
        VALUE_SIZE: 32                          # int or random
        MAX_KEY_SIZE: 16384                                     # int
        MAX_VALUE_SIZE: 32768                           # int
        INDEX_FID: <7800000000000001:b> # fid
        PUT:  40                                                        # int (in percentage)
        DEL:  20                                                        # int (in percentage)
        GET:  20                                                        # int (in percentage)
        NEXT: 20                                                        # int (in percentage)
        LOG_LEVEL: 4                                            # err(0), warn(1), info(2), trace(3), debug(4)

```
