### ISSUE TITLE
FOL record is decoded and printed to stdout from Motr server process

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#900]
- The purpose of the task is to understand what is currently added to FOL
    records
  - The task

    - Use Motr, Hare, m0crate setup
    - run ``m0crate`` with DIX PUT workload
    - print FOL records
    - decode ``m0_fol_frag::rp_data`` using xcode. Use ``be_fmt_decode()`` as
      an example

  - Definition of done

    - cluster CDF and ``hctl status`` output are posted to this issue
    - ``m0crate`` configuration file is posted to this issue
    - output with decoded ``m0_fol_frag::rp_data`` for ``m0crate`` DIX PUT
      workload is posted to this issue

**Comment by somnathbghule** [comment]
We are interested in the content of fol record,
fol record contains a list of all FOL record fragments in a record.

```
	struct m0_fol_rec {
		...
		struct m0_tl  fr_frags;
		....
	} 
```
Each fol frag contains pointer to the data (fol record fragment for a fop).

```
struct m0_fol_frag {
	...
	void  *rp_data;
	...
}	
```
fol record fragment for a fop (struct m0_fop_fol_frag) contains fop opcode and fop data pointer,
In KVS data case fop data pointer == m0_cas_op  pointer, so we could access kv records(struct m0_cas_rec). 

While exploring the fol record content stdout one issue noticed as,

**What is the issue?**
In CAS_DONE phase kv record buffers are finalized and no longer accessible after this phase, because of kv buffer finalization we could not access buffers in  M0_FOPH_FOL_REC_ADD phase. In M0_FOPH_FOL_REC_ADD phase execution motr call to m0_dtx_fol_add() and m0_fol_fdmi_post_record().

We would need to fix issue to access kv records in M0_FOPH_FOL_REC_ADD phase.

```
2287 static int cas_done(struct cas_fom *fom, struct m0_cas_op *op,
2288                     struct m0_cas_rep *rep, enum m0_cas_opcode opc)
2289 {
2290         struct m0_cas_rec *rec_out;
2291         struct m0_cas_rec *rec;
2292         int                ctg_rc = m0_ctg_op_rc(&fom->cf_ctg_op);
...
2341
2342         if (at_fini) {
2343                 /* Finalise input AT buffers. */
2344                 cas_at_fini(&rec->cr_key);
2345                 cas_at_fini(&rec->cr_val);
2346         }

1736 M0_INTERNAL int m0_fom_fol_rec_add(struct m0_fom *fom)
1737 {
.....
1741
1742     rc = m0_dtx_fol_add(&fom->fo_tx);
1743     if (rc != 0)
1744         goto done;
1745
1746 #ifndef __KERNEL__
1747     rc = m0_fol_fdmi_post_record(fom);
1748     if (rc != 0)
1749         goto done;
1750 #endif

```

**Comment by somnathbghule** [comment]
Task completion list:

1. cluster CDF and hctl status output are posted to this issue
```
# Cluster Description File (CDF).
# See `cfgen --help-schema` for the format description.

nodes:
  - hostname: localhost     # [user@]hostname
    data_iface: eth1        # name of data network interface
    #data_iface_type: o2ib  # type of network interface (optional);
                            # supported values: "tcp" (default), "o2ib"
    m0_servers:
      - runs_confd: true
        io_disks:
          data: []
      - io_disks:
          #meta_data: /path/to/meta-data/drive
          meta_data: /dev/sdb
          #meta_data: /mnt/kvs-md
          #meta_data:  /dev/loop0
          data:
            # - /mnt/kvs-d
             - /dev/sdc
             - /dev/sdd
            #- /dev/sde
            #- /dev/loop0
            #- /dev/loop0
            #- /dev/loop1
            #- /dev/loop2
            #- /dev/loop3
            #- /dev/loop4
            #- /dev/loop5
            #- /dev/loop6
            #- /dev/loop7
            #- /dev/loop8
            #- /dev/loop9
    m0_clients:
      s3: 0         # number of S3 servers to start
      other: 2      # max quantity of other Motr clients this host may have
pools:
  - name: the_pool
    #type: sns  # optional; supported values: "sns" (default), "dix", "md"
    #disk_refs:
    #  - { path: /dev/loop0, node: localhost }
    #  - path: /dev/loop1
    #  - path: /dev/loop2
    #  - path: /dev/loop3
    #  - path: /dev/loop4
    #  - path: /dev/loop5
    #  - path: /dev/loop6
    #  - path: /dev/loop7
    #  - path: /dev/loop8
    #  - path: /dev/loop9
    data_units: 1
    parity_units: 0
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
#profiles:
#  - name: default
#    pools: [ the pool ]

[root@devvm temp]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x1f 'the_pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x37 'default': 'the_pool' None None
Services:
    localhost  (RC)
    [started]  hax        0x7200000000000001:0x6   192.168.52.53@tcp:12345:1:1
    [started]  confd      0x7200000000000001:0x9   192.168.52.53@tcp:12345:2:1
    [started]  ioservice  0x7200000000000001:0xc   192.168.52.53@tcp:12345:2:2
    [unknown]  m0_client  0x7200000000000001:0x19  192.168.52.53@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x1c  192.168.52.53@tcp:12345:4:2
```
2.  m0crate configuration file
```
# m0crate index .yaml
# Number of clients and server nodes - TBD. Layout with replication factor 1.
# Keys order: ordered.

CrateConfig_Sections: [MOTR_CONFIG, WORKLOAD_SPEC]

MOTR_CONFIG:
   MOTR_LOCAL_ADDR: 192.168.52.53@tcp:12345:4:1
   MOTR_HA_ADDR:    192.168.52.53@tcp:12345:1:1
   PROF: <0x7000000000000001:0x37>      # Profile fid
   LAYOUT_ID: 1                         # Defines the UNIT_SIZE (9: 1MB)
   IS_OOSTORE: 1                        # Is oostore-mode?
   IS_READ_VERIFY: 0                    # Enable read-verify?
   TM_RECV_QUEUE_MIN_LEN: 16                    # Minimum length of the receive queue
   M0_MAX_RPC_MSG_SIZE: 262144                  # Maximum rpc message size
   PROCESS_FID: <0x7200000000000001:0x19>
   IDX_SERVICE_ID: 1

WORKLOAD_SPEC:                                  # Workload specification section
   WORKLOAD:                                    # First Workload
        WORKLOAD_TYPE: 0                        # Index(0), IO(1)
        WORKLOAD_SEED: tstamp                   # SEED to the random number generator
        NUM_KVP: 2                                      # int
        NXRECORDS: default                                      # int or default
        OP_COUNT: 2                                     # int [units] or unlimited, total operations count.
        EXEC_TIME: unlimited                    # int (seconds) or unlimited
        WARMUP_PUT_CNT: 0                               # int (ops) or all
        WARMUP_DEL_RATIO: 0                     # int (ops / ratio)
        KEY_PREFIX: 1                                   # int or random
        KEY_ORDER:  ordered                     # ordered or random
        KEY_SIZE: 20                                    # int or random
        VALUE_SIZE: 32                          # int or random
        MAX_KEY_SIZE: 16384                                     # int
        MAX_VALUE_SIZE: 32768                           # int
        INDEX_FID: <7800000000000001:2> # fid
        PUT:  100                                                       # int (in percentage)
        DEL:  00                                                        # int (in percentage)
        GET:  00                                                        # int (in percentage)
        NEXT: 00                                                        # int (in percentage)
        LOG_LEVEL: 4                                            # err(0), warn(1), info(2), trace(3), debug(4)

  [root@devvm temp]# mcrate -S /tmp/m0crate-index-1024-16384.yaml
  info: starting workload 0
  info: workload type          index/3
  info: random seed:           0
  info: number of threads:     1
  trace: dix: ops remaining: [2, 0, 0, 0]
  dbg: dix: len = 4, map = {0000}
  dbg: dix: nr_kv_per_op: 2
  dbg: dix: starting_key_num=0
  dbg: dix: Generated k=AAAA:<1:0>,v=9kvfgG2dd4gDiNmGOrYbpxuInJy1a38
  dbg: dix: Generated k=AAAA:<1:1>,v=jlDyBhBOvF36YQsCCTyNg6gZrZxq9yy
  trace: dix: Executed op: put
``` 
3. output with decoded m0_fol_frag::rp_data for m0crate DIX PUT 
```
                        struct m0_fop_fol_frag: 0x7fcbc8053bb0{
                                ffrp_fop_code: 231
                                ffrp_rep_code: 234
                                struct m0_cas_op: 0x7fcbc8053bd0 {
                                                fid:<5400000200000001:2>
                                        struct m0_cas_recv: {
                                                cr_nr: 2

                                                cr_key: 20 bytes AAAA^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
                                                cr_val: 32 bytes 9kvfgG2dd4gDiNmGOrYbpxuInJy1a38^@
                                                cr_key: 20 bytes AAAA^A^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@
                                                cr_val: 32 bytes jlDyBhBOvF36YQsCCTyNg6gZrZxq9yy^@
                                        }
                                                cg_flags: 8
                                }
                        }
                        rp_magic: 3733103530771082103
                        rp_flag: 1
                }
        struct m0_fdmi_src_rec {
                fsr_magic: 140513974254722
                struct *m0_fdmi_src fsr_src =(nil){
                }
                fsr_rec_id:7fcbebffe910:7fcbf58ebe49
                fsr_matched: 26
                fsr_dryrun: 161
        }
```
